name: PMO Summary from repo file
on:
  push:
    branches: [ main ]
    paths: [ 'kpi_export.*' ]     # run only when CSV/XLSX changes
  workflow_dispatch:              # manual run button
  schedule:
    - cron:  '0 5 * * *'          # optional daily run if file is already present

jobs:
  summarise:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Run summariser
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python summary.py kpi_export.csv   # or .xlsx
      #                                   ↑ same name every run

    - name: Send summary e-mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "Daily PMO RAG Summary"
        to: ${{ secrets.EMAIL_TO }}
        from: "PMO Bot"
        content_type: text/plain
        body_file: SUMMARY_EMAIL.txt
