jobs:
  summarise:
    runs-on: ubuntu-latest
    env:                          # 👈 makes HF_TOKEN visible to every step
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Run summariser
      run: python summary.py kpi_export.csv

    # Optional: peek at the file (good for first test)
    - name: Debug – show summary file
      run: head -20 SUMMARY_EMAIL.txt

    - name: Send summary e-mail
      if: always()                       # still fires on failure
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true                    # TLS on connect
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "Daily PMO RAG Summary – ${{ job.status }}"
        to: ${{ secrets.EMAIL_TO }}
        from: "PMO Bot <${{ secrets.EMAIL_USER }}>"
        body: file://SUMMARY_EMAIL.txt
