name: PMO Summary from repo file          # free-form name shown in Actions tab

on:                                       # WHEN should the workflow run?
  push:                                   # ① every push to main
    branches: [ main ]
  workflow_dispatch:                      # ② manual “Run workflow” button
  schedule:                               # ③ daily at 05:00 UTC (10:00 PKT)
    - cron:  '0 5 * * *'

jobs:
  summarise:
    runs-on: ubuntu-latest
    env:                                  # makes HF_TOKEN visible in all steps
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run summariser
        run: python summary.py kpi_export.csv

      - name: Debug – show summary file    # good for the first test
        run: head -30 SUMMARY_EMAIL.txt

      - name: Send summary e-mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          to: ${{ secrets.EMAIL_TO }}
          from: "PMO Bot <${{ secrets.EMAIL_USER }}>"
          subject: "Daily PMO Effort-Variance Report – ${{ job.status }}"

          body: |
            Hello Team,

            Below is today’s effort-variance snapshot generated by the PMO pipeline
            (branch **${{ github.ref_name }}**, run #${{ github.run_number }}).

            file://SUMMARY_EMAIL.txt        # ⬅️ inlines the cleaned summary block

            **Next steps**
            • Review the items above and confirm root causes.  
            • Add recovery actions or updated ETAs to the project tracker
              before **17:00 PKT** today.

            Thanks,  
            **Hafiza Maham**

            —  
            _This is an automated message sent from GitHub Actions.
            Reply here only if you need assistance; otherwise, update the tracker._
      - name: Clean up summary files          # ← add this block
        if: always()                          # runs even if mail fails
        run: |
           rm -f SUMMARY_EMAIL.txt EMAIL_BODY.txt
